import Head from 'next/head';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import { MouseEvent, useState } from 'react';
import { v4 as uuidv4 } from 'uuid';

interface ITodo {
  id: string;
  content: string;
  completed: boolean;
}

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const [todos, setTodos] = useState<ITodo[]>([]);

  const onClickButton = (e: MouseEvent) => {
    e.preventDefault();
    setTodos((state) => [
      ...state,
      {
        id: uuidv4(),
        content: (e.target as HTMLInputElement).value,
        completed: false,
      },
    ]);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles['todo-page']}>
        <form className={styles.form}>
          <label htmlFor="input" className={styles.label}>
            <div className={styles['todo__title']}>할 일 입력하기</div>
            <input type="text" className={styles['todo__input']} id="input" />
          </label>

          <button type="submit" className={styles['todo__button']} onClick={onClickButton}>
            CLICK
          </button>
        </form>

        <ul className="list">
          {todos.map((todo) => (
            <div key={todo.id}>{todo.content}</div>
          ))}
        </ul>
      </main>
    </>
  );
}
